name: Xcode - Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run unit tests using xcodebuild
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Unit Tests
        run: |
          xcodebuild test -project birch.xcodeproj -scheme birch -destination 'platform=iOS Simulator,name=iPhone 17 Pro' -only-testing:birchTests -parallel-testing-enabled NO CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}
